title: Operating Systems Journal
description: My Weekly Labs, Setup Notes, and Screenshots (UoR)
Author: Richard Akole (RIC22599703)
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
